# CMake generated Testfile for 
# Source directory: /Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn
# Build directory: /Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/modules/dnn
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_dnn "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/bin/opencv_test_dnn" "--gtest_output=xml:opencv_test_dnn.xml")
set_tests_properties(opencv_test_dnn PROPERTIES  LABELS "Main;opencv_dnn;Accuracy" WORKING_DIRECTORY "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVUtils.cmake;1154;add_test;/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVModule.cmake;1168;ocv_add_test_from_target;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;80;ocv_add_accuracy_tests;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_perf_dnn "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml")
set_tests_properties(opencv_perf_dnn PROPERTIES  LABELS "Main;opencv_dnn;Performance" WORKING_DIRECTORY "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/test-reports/performance" _BACKTRACE_TRIPLES "/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVUtils.cmake;1154;add_test;/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVModule.cmake;1090;ocv_add_test_from_target;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;81;ocv_add_perf_tests;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_sanity_dnn "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_dnn PROPERTIES  LABELS "Main;opencv_dnn;Sanity" WORKING_DIRECTORY "/Users/hyunggeunahn/Downloads/opencv-3.4.0/build-shared/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVUtils.cmake;1154;add_test;/Users/hyunggeunahn/Downloads/opencv-3.4.0/cmake/OpenCVModule.cmake;1091;ocv_add_test_from_target;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;81;ocv_add_perf_tests;/Users/hyunggeunahn/Downloads/opencv-3.4.0/modules/dnn/CMakeLists.txt;0;")
